FROM berliozcloud/node-9

COPY src /app
RUN npm install

EXPOSE 55555

# FROM node:carbon

# # RUN apt-get update && apt-get install -y vim

# ENV NODE_PATH=/usr/local/lib/node_modules

# COPY ./ /src/

# WORKDIR /src
# RUN npm install
# RUN npm install --only=dev

# CMD ["node", "."]
